bridges = []
persistence_dir = ".holochain/holo"

[[agents]]
id = "hp-admin-agent"
keystore_file = "agent.key"
name = "HP Admin"
public_address = "HcSCjCvkR5uywn6z5t9SBFtTs7p83Ex3urUtpY8jsUa7pn3zdF6XJU4U6tuzpui"

[[dnas]]
file = "/nix/store/jinsv02qykq3l6kl7l8b857cs423658k-holofuel/holofuel.dna.json"
hash = "QmUnUf3J49qv3ujzYAVEWXC6WZZsQTgm3KvtYAMJDZ4Z2P"
id = "holofuel-dna"

[[instances]]
agent = "hp-admin-agent"
dna = "holofuel-dna"
id = "holofuel"

[instances.storage]
path = ".holochain/holo/storage/hp-admin-agent/holofuel"
type = "lmdb"


# Hosted Anonymous Agent
# [[instances]]
# agent = "holofuel-agent-1"
# dna = "holofuel-dna"
# id = "hhaId::holofuel"

# [instances.storage]
# path = ".holochain/holo/storage/holofuel-agent-1/holofuel"
# type = "lmdb"

# Hosted Agent
# [[instances]]
# agent = "hosted-holofuel-agent"
# dna = "holofuel-dna"
# id = "hhaId::HcScjtXGDA8frfw8v3fOtDeTBmoynnb8f3tpMvJrRq5gq6mn4er966B43Uv5SFZ-holofuel"

# [instances.storage]
# path = ".holochain/holo/storage/hosted-holofuel-agent/holofuel"
# type = "lmdb"

[[interfaces]]
id = "websocket-interface"

[interfaces.driver]
port = 33000
type = "websocket"

[[interfaces.instances]]
id = "holofuel"

# [[interfaces.instances]]
# id = "hhaId::HcScjtXGDA8frfw8v3fOtDeTBmoynnb8f3tpMvJrRq5gq6mn4er966B43Uv5SFZ-holofuel"

# [[interfaces.instances]]
# id = "hhaId::holofuel"

[[interfaces]]
admin = true
id = "http-interface"

[interfaces.driver]
port = 34000
type = "http"

[[interfaces.instances]]
id = "holofuel"

# [[interfaces.instances]]
# id = "hhaId::HcScjtXGDA8frfw8v3fOtDeTBmoynnb8f3tpMvJrRq5gq6mn4er966B43Uv5SFZ-holofuel"

# [[interfaces.instances]]
# id = "hhaId::holofuel"

[logger]
type = "debug"

[logger.rules]

[[logger.rules.rules]]
color = "red"
exclude = false
pattern = "^err/"

[[logger.rules.rules]]
color = "white"
exclude = false
pattern = "^debug/dna"

[network]
sim2h_url = "ws://localhost:9000"
type = "sim2h"
