bridges = []
persistence_dir = ".holochain/holo"

[[agents]]
id = "hp-admin-agent"
keystore_file = "agent.key"
name = "HP Admin"
public_address = "HcSCjCvkR5uywn6z5t9SBFtTs7p83Ex3urUtpY8jsUa7pn3zdF6XJU4U6tuzpui"

# [[dnas]]
# file = "/nix/store/kgnrlr17660mxmdjqpz1m5fk728mm2c1-holofuel/holofuel.dna.json"
# hash = "QmbAn6yLya5dFWJp8CccgT6EyPtrNKGVnYScYJsh3RBvEq"
# id = "holofuel-dna"

[[dnas]]
file = "dna/dist/holofuel.dna.json"
hash = "QmQ5bxqrTcS7pQZqqVDKmND4S7RobzhDkH3PgeKD2kKFv9"
id = "holofuel-dna"

[[instances]]
agent = "hp-admin-agent"
dna = "holofuel-dna"
id = "holofuel"

[instances.storage]
path = ".holochain/holo/storage/hp-admin-agent/holofuel"
type = "lmdb"

[[interfaces]]
id = "websocket-interface"

[interfaces.driver]
port = 3400
type = "websocket"

[[interfaces.instances]]
id = "holofuel"

[[interfaces]]
admin = true
id = "http-interface"

[interfaces.driver]
port = 3300
type = "http"

[[interfaces.instances]]
id = "holofuel"

[logger]
type = "debug"

[logger.rules]

[[logger.rules.rules]]
color = "red"
exclude = false
pattern = "^err/"

[[logger.rules.rules]]
color = "white"
exclude = false
pattern = "^debug/dna"

[network]
sim2h_url = "ws://localhost:9000"
type = "sim2h"
