// export const HOME_PATH = 'home'
export const INBOX_PATH = 'inbox'
export const OFFER_REQUEST_PATH = 'offer-request'
export const HISTORY_PATH = 'history'
export const PROFILE_PATH = 'profile'
export const HP_ADMIN_DASHBOARD_PATH = '/admin/dashboard'
