export const HOME_PATH = 'home'
export const INBOX_PATH = 'inbox'
export const OFFER_REQUEST_PATH = 'offer-request'
export const HISTORY_PATH = 'history'
export const PROFILE_PATH = 'profile'
export const TOS_PATH = 'tos'
