export const HOME_PATH = 'home'
export const INBOX_PATH = 'inbox'
export const OFFER_PATH = 'offer'
export const REQUEST_PATH = 'request'
export const HISTORY_PATH = 'history'
export const TOS_PATH = 'tos'
