query AllHoloFuelPendingTransactions {
  allHoloFuelPendingTransactions {
    originTimeStamp
    originEvent
    counterparty
    txAuthor
    amount
    fee
    event
    status
    transaction_timestamp
    eventCommitHash
    dueDate
    notes
    originCommitHash
    promiseCommitSignature
    inResponseToTX
  }
}