query AllHPSettings {
  allHPSettings {
    hostName
    hostPubKey
    hostEmail
    deviceName
    networkId
    sshAccess
    deviceAdminPort
    hcAdminPort
    hostingPort
    hcNetworkPort
  }
}