mutation HolofuelCancelMutation ($transactionId: ID) {
  holofuelCancel(transactionId: $transactionId) {
    id
    amount
    counterparty { agentAddress, nickname, avatarUrl }
    direction
    status
    type
    timestamp
    fees
    presentBalance
    notes
  }
}
