mutation HolofuelDeclineMutation ($transactionId: ID) {
  holofuelDecline(transactionId: $transactionId) {
    id
    amount
    counterparty { agentAddress, nickname, avatarUrl }
    direction
    status
    type
    timestamp
    isActioned
  }
}
