query HolofuelWaitingTransactionsQuery {
  holofuelWaitingTransactions {
    id @client(always: true)
    amount
    counterparty { id }
    direction
    status
    type
    timestamp
    notes
    fees
  }
}
