query HolofuelActionableTransactionsQuery {
  holofuelActionableTransactions {
    id
    amount
    counterparty { id, nickname }
    direction
    status
    type
    timestamp
    notes
    fees
    canceledBy { id, nickname }
  }
}
