mutation HolofuelAcceptOfferMutation ($transactionId: ID) {
  holofuelAcceptOffer(transactionId: $transactionId) {
    id
    amount
    counterparty { agentAddress, nickname, avatarUrl }
    direction
    status
    type
    timestamp
    inProcess
    isActioned
    isStale 
  }
}
