mutation HolofuelRequest ($counterpartyId: String, $amount: Float, $notes: String) {
  holofuelRequest(counterpartyId: $counterpartyId, amount: $amount, notes: $notes) {
    id
    amount
    counterparty { id }
    notes
    direction
    status
    type
    timestamp
  }
}
