mutation HolofuelAcceptOfferMutation ($transactionId: ID) {
  holofuelAcceptOffer(transactionId: $transactionId) {
    id
    amount
    counterparty { id, nickname, avatarUrl }
    direction
    status
    type
    timestamp
    pendingCompletion
    actioned
    stale
  }
}
