mutation HolofuelDeclineMutation ($transactionId: ID) {
  holofuelDecline(transactionId: $transactionId) {
    id
    amount
    counterparty { id, nickname }
    direction
    status
    type
    timestamp
  }
}
