query HolofuelCompletedTransactionsQuery {
  holofuelCompletedTransactions {
    id
    amount
    counterparty { id }
    direction
    status
    type
    timestamp
    fees
    presentBalance
    notes
  }
}
