query HolofuelWaitingTransactionsQuery {
  holofuelWaitingTransactions {
    id
    amount
    counterparty { agentAddress, nickname, avatarUrl }
    direction
    status
    type
    timestamp
    notes
  }
}
