query HolofuelNewCompletedTransactionsQuery($since: String!) {
  holofuelNewCompletedTransactions(since: $since) {
    id
    amount
    counterparty { id }
    direction
    status
    type
    timestamp
    fees
    presentBalance
    notes
  }
}
