mutation HolofuelOfferMutation ($counterparty: String, $amount: Float, $notes: String, $requestId: ID) {
  holofuelOffer(counterparty: $counterparty, amount: $amount, notes: $notes, requestId: $requestId) {
    id
    amount
    counterparty
    direction
    status
    type
    timestamp
  }
}
