mutation HolofuelOffer ($offer: TransactionInput) {
  holofuelOffer(offer: $offer) {
    id
    amount
    counterparty { agentAddress, nickname, avatarUrl }
    notes
    direction
    status
    type
    isActioned
    timestamp
  }
}
