mutation holofuelRefundDeclined ($transactionIds:[CancelDeclinedTransactionsInput]) {
  holofuelRefundDeclined (transactionIds: $transactionIds) {
    id
    amount
    counterparty { id, nickname }
    direction
    status
    type
    timestamp
    fees 
    presentBalance
    notes
  }
}
