query HolofuelNonPendingTransactionsQuery {
  holofuelNonPendingTransactions {
    id
    amount
    counterparty { agentAddress, nickname, avatarUrl }
    direction
    status
    type
    timestamp
    presentBalance
    notes
    inProcess
  }
}
