query HolofuelRecentTransactionsQuery {
  holofuelRecentTransactions {
    id
    amount
    counterparty { id }
    direction
    status
    type
    timestamp
    dateLabel
    fees
    presentBalance
    notes
  }
}
