mutation HolofuelRequest ($request: TransactionInput) {
  holofuelRequest(request: $request) {
    id
    amount
    counterparty { agentAddress, nickname, avatarUrl }
    notes
    direction
    status
    type
    timestamp
  }
}
