query HolofuelEarningsTransactionsQuery {
  holofuelEarningsTransactions {
    id
    amount
    counterparty { id }
    direction
    status
    type
    timestamp
    fees
    presentBalance
    notes
    happName
  }
}
