query HolofuelNewCompletedTransactionsQuery($since: String) {
  holofuelNewCompletedTransactions(since: $since) {
    id
    amount
    counterparty { agentAddress, nickname, avatarUrl }
    direction
    status
    type
    timestamp
    presentBalance
    notes
  }
}
