query HolofuelWaitingTransactionsQuery {
  holofuelWaitingTransactions {
    id
    amount
    counterparty { id, nickname, avatarUrl }
    direction
    status
    type
    timestamp
    notes
    fees
  }
}
