query HolofuelActionableTransactionsQuery {
  holofuelActionableTransactions {
    id
    amount
    counterparty { id }
    direction
    status
    type
    timestamp
    dateLabel
    notes
    fees
  }
}
