query HolofuelCompleteTransactionsQuery {
  holofuelCompleteTransactions {
    id
    amount
    counterparty
    direction
    status
    type
    timestamp
    fees
    presentBalance
    notes
  }
}
