mutation HposUpdateVersion ($availableVersion: String) {
  hposUpdateVersion (availableVersion: $availableVersion) {
    versionInfo { availableVersion { rev }, currentVersion { rev } }
    networkId
    ports { primaryPort }
  }
}
