mutation HposUpdateVersion ($availableVersion: String, $currentVersion: String) {
  hposUpdateVersion (availableVersion: $availableVersion, currentVersion: $currentVersion) {
    versionInfo { availableVersion, currentVersion }
    networkId
    ports { primaryPort }
  }
}
