mutation UpdateHPSettings ($HpSettings:HpSettings ) {
  updateHPSettings(allHPSettings: $HpSettings) {
    hostName
    hostPubKey
    hostEmail
    deviceName
    networkId
    sshAccess
    ports
  }
}
