mutation UpdateHPSettings ($newHPSettings: HpSettingsInput ) {
  updateHPSettings(newHPSettings: $newHPSettings) {
    hostName
    hostPubKey
    hostEmail
    deviceName
    networkId
    sshAccess
    deviceAdminPort
    hcAdminPort
    hostingPort
    hcNetworkPort
  }
}