mutation UpdateHPSettings ($HpSettingsInput: HpSettingsInput ) {
  updateHPSettings(newHPSettings: $HpSettingsInput) {
    hostName
    hostPubKey
    hostEmail
    deviceName
    networkId
    sshAccess
    ports
  }
}
